# -*- coding: utf-8 -*-
"""Arun Thiru_BC2406_CBA Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dfjIQcJi6XIcalon4s9U6TcicvHG_J0s
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

#Upload the dataset
print("Please upload your homeloan4.csv file:")
uploaded = files.upload()

#Load the dataset into a Pandas DataFrame
df = pd.read_csv('homeloan4.csv')
print("\nData loaded successfully!")

# Display basic info and missing values
print("--- Dataset Info ---")
df.info()

print("\n--- Summary Statistics ---")
display(df.describe(include='all'))

print("\n--- Missing Values Check ---")
print(df.isnull().sum())

# Visualize distribution
plt.figure(figsize=(6, 4))
sns.countplot(data=df, x='Loan_Status', palette='viridis')
plt.title('Target Variable Distribution (Loan_Status)')
plt.show()

df_clean = df.copy()

#Eliminate Loan_ID as it provides no value to this analysis
df_clean.drop('Loan_ID', axis=1, inplace=True, errors='ignore')

# Impute missing numeric/ordinal values with median
for col in ['Loan_Amount_Term', 'Credit_Score']:
    if df_clean[col].isnull().sum() > 0:
        df_clean[col].fillna(df_clean[col].median(), inplace=True)

# Categorical values to be impute with mode
for col in ['Gender', 'Married', 'Dependents', 'Self_Employed']:
    if df_clean[col].isnull().sum() > 0:
        df_clean[col].fillna(df_clean[col].mode()[0], inplace=True)

print("Missing Values After Cleaning")
print(df_clean.isnull().sum())

# Convert text to numbers
le = LabelEncoder()
cat_cols = ['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'Property_Area', 'Loan_Status']
for col in cat_cols:
    df_clean[col] = le.fit_transform(df_clean[col])

# Separate features (X) and target (y)
X = df_clean.drop('Loan_Status', axis=1)
y = df_clean['Loan_Status'] # 1 = Y (Approved), 0 = N (Rejected)

# Train/Test Split (70% Train, 30% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print("\nData cleaned, encoded, and split successfully!")

# CART MODEL
# Train the model (maximum depth will be 4 to prevent overfitting)
cart_model = DecisionTreeClassifier(max_depth=4, random_state=42)
cart_model.fit(X_train, y_train)

# Evaluate
cart_pred = cart_model.predict(X_test)
cart_acc = accuracy_score(y_test, cart_pred)
cart_size = cart_model.get_n_leaves()

print("================ CART MODEL ================")
print(f"CART Size (Number of leaves): {cart_size}")
print(f"CART Test Accuracy: {cart_acc:.4f}\n")

# Plot Decision Tree
plt.figure(figsize=(20, 10))
plot_tree(cart_model, feature_names=X.columns, class_names=['Reject', 'Approve'], filled=True, rounded=True, fontsize=10)
plt.title("CART Decision Tree")
plt.show()



# LOGISTIC REGRESSION MODEL
# Train the model
log_model = LogisticRegression(max_iter=1000, random_state=42)
log_model.fit(X_train, y_train)

# Evaluate
log_pred = log_model.predict(X_test)
log_acc = accuracy_score(y_test, log_pred)
log_size = len(log_model.coef_[0]) # Number of coefficients

print("LOGISTIC REGRESSION MODEL")
print(f"Logistic Regression Size (Number of Coefficients): {log_size}")
print(f"Logistic Regression Test Accuracy: {log_acc:.4f}\n")

# Display the coefficients clearly
coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': log_model.coef_[0]
}).sort_values(by='Coefficient', ascending=False)

print("Logistic Regression Coefficients:")
display(coef_df)

"""1. Exploratory Data Analysis and Important Findings
Dataset Overview:
The dataset contains 592 home loan applications with 13 variables (including the target Loan_Status).

Key Findings:

Target Variable Distribution: The dataset is somewhat imbalanced. About 69.6% of the loans were approved ('Y'), while 30.4% were rejected ('N'). This means a naive model predicting 'Y' every time would be 69.6% accurate.

Missing Values: There are several missing values that need addressing before modeling:

Categorical: Gender (13), Married (2), Dependents (13), Self_Employed (31).

Numerical/Ordinal: Loan_Amount_Term (14), Credit_Score (49).

Demographic Insights: The majority of the applicants are Male, Married, Graduates, and not Self-Employed.

Financial Insights: * ApplicantIncome is heavily right-skewed, with an average of ~$5,404, but ranging from $150 to a massive $81,000.

Credit_Score is binary (0 or 1), and a large majority (~84%) of applicants have a good credit score (1.0).

2. Data Cleaning and Preparation Plan
To improve data quality and prepare it for Machine Learning, the following steps are justified and were executed:

Drop Unnecessary Columns: * Action: Removed Loan_ID.

Justification: It is a unique identifier string for each applicant and possesses no predictive power. Keeping it could confuse the algorithm.

Imputation of Missing Values:

Action (Categorical): Filled missing values in Gender, Married, Dependents, and Self_Employed with the mode (most frequent class).

Action (Numerical): Filled missing values in Loan_Amount_Term and Credit_Score with the median.

Justification: Standard statistical imputation prevents the loss of valuable rows. Median is preferred over mean for numerical variables here to ensure we are robust against extreme outliers (e.g., the applicant with $81,000 income).

Encoding Categorical Variables:

Action: Applied Label Encoding to map text categories (e.g., Yes/No, Male/Female, Graduate/Not Graduate, Property Area) into numeric values (0, 1, 2).

Justification: Algorithms like Logistic Regression and CART require all input variables to be strictly numeric.

3. Model Application and Memo
CART Model Size: 12 leaf nodes (Max depth restricted to 4).

Logistic Regression Model Size: 11 coefficients (one for each input feature).

MEMO
To: Chief Executive Officer, Digital Bank
From: Data Analytics Team
Subject: Feasibility of Automating Home Loan Approvals using Machine Learning

Dear CEO,

We have concluded our preliminary analytics to test the feasibility of automating the home loan approval process using our historical data of 592 applicants. I am pleased to report that the initiative shows strong potential.

We developed and compared two predictive models: a Decision Tree (CART) and a Logistic Regression model. Both models achieved an accuracy of approximately 83% on unseen test data, meaning they correctly approve or reject 8 out of 10 applications based purely on historical patterns.

Relevant Findings:

Credit Score is King: Across our analysis, having a good Credit_Score is by far the strongest predictor of loan approval. The Logistic Regression model weighted this feature heavily above all else.

Socio-Demographic Factors: Being married and being a graduate slightly positively influence the likelihood of approval. Conversely, purchasing property in specific areas has minor negative weights, indicating slight location-based risk.

Income vs. Loan Amount: Interestingly, raw income levels and loan amounts had relatively low direct impact on the model's decision compared to the applicant's credit history.

Recommendation: We recommend moving forward with a pilot program using the Logistic Regression model, as its coefficients provide clear transparency into why an applicant was approved or rejected, which is crucial for regulatory compliance in banking.

4. Overfitting Analysis
Did your model overfit? Explain.

No, our models did not overfit. Overfitting occurs when a machine learning algorithm memorizes the training data—capturing noise and outliers—resulting in near-perfect accuracy on the training set but poor generalization and low accuracy on unseen testing data.

In our execution, the data was split into a 70% training set and a 30% testing set.

The CART model achieved a training accuracy of ~82.85% and a testing accuracy of ~83.15%.

The Logistic Regression model achieved a training accuracy of ~81.16% and a testing accuracy of ~83.15%.

Because the models perform equally well (and in fact, marginally better) on the unseen test data compared to the training data, it proves they have generalized the underlying patterns effectively. To explicitly prevent the CART model from overfitting, we applied "pruning" by restricting its maximum depth to 4, stopping it from creating a highly complex tree tailored only to the training set.

5. Improving Analytics Success
What can be done to improve the success of such Analytics in the bank?

To ensure the long-term success of this Analytics initiative, the bank should focus on:

Data Enrichment: The current dataset is somewhat basic. Collecting supplementary data such as existing debt-to-income ratios, length of current employment, and alternative credit data (e.g., utility bill payments) will significantly boost the model’s predictive power.

Addressing Imbalance: Since ~70% of historical loans were approved, the models are naturally biased toward approving loans. Techniques like oversampling minority cases (SMOTE) or adjusting class weights should be implemented to make the model better at identifying high-risk rejections.

Explainable AI (XAI): Customers and regulators demand transparency. The bank must implement XAI frameworks to clearly explain to rejected applicants exactly which factors (e.g., insufficient co-applicant income) led to the automated decline.

Continuous Monitoring: Economic conditions change. The models must be continuously monitored for "concept drift" and retrained periodically with fresh data to ensure they remain accurate during different economic cycles.
"""